### PR TITLE
Add jmx-exporter monitoring functionality with servicemonitor

### PR DESCRIPTION
**Pull request by azisi**

### CODE REVIEW

**Comment by valeriano-manassero** [comment]
Hi, Ty for the PR. Pls increment minor version in Chart yank and regenerate README with helm-docs to pass tests.

**Comment by azisi** [comment]
Oops sorry about that, this just a draft.
I wanted to open the PR in my repo first to clean it up before I open it here 😄

**Comment by valeriano-manassero** [comment]
No worries and take your time, will merge it when ready 😄

**Comment by valeriano-manassero** [comment]
I suggest to change version to 2.7.0 instead of 2.6.2.
This is because some new parameter is added so it's not just a patch.
wdyt?

**Comment by azisi** [comment]
> No worries and take your time, will merge it when ready 😄

done!
btw, i think the lint step in ci.yaml is broken. There is no v1.12.0 helm-docs version.

**Comment by valeriano-manassero** [comment]
> i think the lint step in ci.yaml is broken. There is no v1.12.0 helm-docs version.

Good catch, would you mind to change this line with 1.11.0 too pls? https://github.com/valeriano-manassero/helm-charts/blob/549224ca3088c79108cb7623c0f2d4afa1154bdc/.github/helm-docs.sh#L4

**Comment by valeriano-manassero** [comment]
I suggest to change version to 2.7.0 instead of 2.6.2.
This is because some new parameter is added so it's not just a patch.
wdyt?

**Comment by azisi** [comment]
Should we update trino version to the latest also, which is 406 from 380 that is now?

**Comment by valeriano-manassero** [comment]
> Should we update trino version to the latest also, which is 406 from 380 that is now?

I have no idea if new version is compatible with the chart.
I suggest just to make this PR to pas tests (helm-docs needs to be run again). Then you can open another PR for a new version.

**Pull request merged**
