### PR TITLE
Add pod annotations

### PR DESCRIPTION
**Pull request by mFeigeInvia**
Allow Custom podAnnotations for something like kube2Iam https://github.com/jtblin/kube2iam#kubernetes-annotation

### CODE REVIEW

**Comment by valeriano-manassero** [comment]
Can you pls bump up MINOR version in Chart.yaml and regenerate README.me with helm-docs. With that I can launch automated tests and eventually merge. Ty!

**Comment by valeriano-manassero** [comment]
@mFeigeInvia can you pls regenerate README.md with helm-docs now?

**Comment by mFeigeInvia** [comment]
> pls don't change any file in old `presto` folder; this is because this folder is there just for legacy reasons and changing it will trigger the CI also for that chart.

sry, it was the helm-docs generate, I will revert

**Comment by valeriano-manassero** [comment]
> > pls don't change any file in old `presto` folder; this is because this folder is there just for legacy reasons and changing it will trigger the CI also for that chart.
> 
> sry, it was the helm-docs generate, I will revert

No worries, it happens to me every time too 👍 launching tests

**Comment by valeriano-manassero** [comment]
Ty for the PR, new version deployed!

**Pull request merged**
