### PR TITLE
Add password authentication to Trino chart

### PR DESCRIPTION
**Pull request by fxulusoy**
I want to add [password file authentication](https://trino.io/docs/current/security/password-file.html) to Trino chart. Let me know what you think.

### CODE REVIEW

**Comment by valeriano-manassero** [comment]
Can you pls rebase your branch?
There was a problem with CI that should be solved now with one action that removed master reference. Checks should be triggered automatically. Btw the PR looks good, ty so much for your effort!

**Comment by valeriano-manassero** [comment]
Can you pls download `helm-docs` v1.5.0 and run it on your local folder? it should generate the new README.md aligned with values automatically.

Helm docs is here: https://github.com/norwoodj/helm-docs/releases

This should fix the lint-docs check.

I will try to add some instructions on how to prepare for a PR soon to avoid frustration while fighting with GitHub actions :)

**Comment by valeriano-manassero** [comment]
It looks every action removed master reference, it's some time I don't update charts so I didn't noticed. My apologies for that. Hopefully this is the last issue that should be fixed, pls can you rebase?

**Comment by fxulusoy** [comment]
No worries. Everything is fine :) 

> It looks every action removed master reference, it's some time I don't update charts so I didn't noticed. My apologies for that. Hopefully this is the last issue that should be fixed, pls can you rebase?

**Comment by valeriano-manassero** [comment]
The chart is now published, version 1.1.2 should get listed in ~30 mins on artifacthub.

Ty so much for your efforts!

**Pull request merged**
