### PR TITLE
Update default server config path 

### LINKED ISSUE #40: Update template to support trino-docker verison 352
Currently, according to [documentation for trino-docker version 351](https://github.com/trinodb/trino/tree/297ba4d58a526667d91b9685b453faafa869c68f/core/docker) configuration is expected to be mounted to either to `/etc/trino` or `/usr/lib/trino/etc` (the latter takes precedence). If neither of these exists then the default single node configuration will be used but in the upcoming release `352` the configuration is expected to only `etc/trino`. So we need to update the helm-charts accordingly as `health_check.sh` is not getting executed because configmap is mounting it as a read-only file under new directory `/etc/trino`

Reference: 
https://github.com/trinodb/trino/blob/master/docs/src/main/sphinx/release/release-351.md#docker-image
https://trino.io/blog/2021/01/04/migrating-from-prestosql-to-trino.html => Docker Image section

### PR DESCRIPTION
**Pull request by aakashnand**
I have tried updating default `server.config.path` in accordance with the latest documentation from trino repository. Please let me know if I made any mistakes or if there is any improvement necessary.

After the migration from `prestosql` to `trino`, the default configuration is being loaded from `/etc/trino`. However, the plugin directory remains the same as `/usr/lib/trino/plugin`. I got this confirmation from trino community slack. 

I am facing one more problem from the updated location `/etc/trino/`, `health_check.sh` is not able to run because of permission-denied error as configmap is mounting it as a read-only file system.  Please suggest me any changes required to fix this as well.

Ref: 
1) https://trinodb.slack.com/archives/CGB0QHWSW/p1611667502072600
2) https://github.com/trinodb/trino/blob/master/docs/src/main/sphinx/release/release-351.md#docker-image

closes #40

### CODE REVIEW

**Comment by valeriano-manassero** [comment]
This PR looks pretty good to me. To pass every check pls bump up the chart version and use `helm-docs` to regenerate README.md right after.

I will be glad to merge it when we will see green light. Thank you!

**Comment by aakashnand** [comment]
@valeriano-manassero I have upgraded the `helm-docs` version and also tried regenerating the README.md but lint-docs is still failing. Could you please help me here?

**Comment by valeriano-manassero** [comment]
Everything is good, simply the Ci is using an old version of helm-docs. Pls edit `.github/helm-docs.sh` changing 
```
HELM_DOCS_VERSION="1.4.0"
```
 to 
```
HELM_DOCS_VERSION="1.5.0"
```
This should be enough to finally get the CI successful

**Comment by aakashnand** [comment]
> Everything is good, simply the Ci is using an old version of helm-docs. Pls edit `.github/helm-docs.sh` changing
> 
> ```
> HELM_DOCS_VERSION="1.4.0"
> ```
> 
> to
> 
> ```
> HELM_DOCS_VERSION="1.5.0"
> ```
> 
> This should be enough to finally get the CI successful

I already did that in my last commit but still not working. https://github.com/valeriano-manassero/helm-charts/pull/41/commits/a5c9d6ae29b2ac6a1628a4bc810ac61d8e6f045d

**Comment by valeriano-manassero** [comment]
You are tight, the problem is helm-docs script is failing on other charts now that we have an updated version. I tried a fix in CI. Pls try to rebase your branch now, hopefully this will finally be enough to get the CI working.

Sorry for the mistake.

**Comment by aakashnand** [comment]
@valeriano-manassero Finally, we have made it. Thank you so much for your help. Looking forward to PR of `health_check.sh`  for me it always fails because of some issue of permissions.

**Comment by valeriano-manassero** [comment]
Thank you very much for your effort. Chart is published. It will appear in artifacthub soon too.

**Pull request merged**
