### PR TITLE
Optional custom connectors-secret

### PR DESCRIPTION
**Pull request by fxulusoy**
I need to define connectors in a custom secret because of security reasons. I don't want to define them in the Helm values.

### CODE REVIEW

**Comment by valeriano-manassero** [comment]
I understand the need, just because I'm curious, are you deploying with any kind of GitOps pipeline? Asking because in that case you can use some sealed secret to push values without exposing them.

**Comment by fxulusoy** [comment]
Hi @valeriano-manassero, 
Yes you are right. I use [Flux](https://fluxcd.io/). I know sealed secrets but as of today we don't use it. Therefore I don't push the credentials in plain text in helm resources definition for Flux to Git. If you think, this is not something you don't want to merge, please let me know. 

Btw, I have run `helm-docs` before my push. I don't understand why it failed on the Git. Any idea?

**Comment by valeriano-manassero** [comment]
> Yes you are right. I use [Flux](https://fluxcd.io/). I know sealed secrets but as of today we don't use it. Therefore I don't push the credentials in plain text in helm resources definition for Flux to Git. If you think, this is not something you don't want to merge, please let me know.

No problem at all, we can get it merged soon, I was just suggesting an alternative in the meanwhile :)

> Btw, I have run `helm-docs` before my push. I don't understand why it failed on the GitHub. Any idea?

Will check in some time and get back to you asap on this (already happened in the past to me :( )

**Comment by valeriano-manassero** [comment]
Can you pls rebase on latest now? I just put some verbose message in CI so we can understand what is going on over there :D

**Comment by valeriano-manassero** [comment]
@fxulusoy sorry to ask again but debugging GH Actions is always a pain for me 😄 : can you pls try to reuse again so hopefully we will get some insightful info?

**Comment by fxulusoy** [comment]
@valeriano-manassero No worries. We are in the same boot :)

**Comment by valeriano-manassero** [comment]
ok, now the issue is real 😄 pls bump up to .12; .11 was used by me yesterday for a small bug fix on NOTES.

**Comment by valeriano-manassero** [comment]
now lgtm but for some reason it didn't got installed on GH action host while it works on my local installation. Will do some more test and then will merge regardless of GH Action result.

**Comment by valeriano-manassero** [comment]
lgtm, I can install the chart without issues on my local env. Will try to do some debug on gh actions asap.

**Pull request merged**
